{% set version = "2.0.7" %}

package:
  name: bob.ip.gabor
  version: {{ version }}

source:
  fn: bob.ip.gabor-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.ip.gabor/bob.ip.gabor-{{ version }}.zip
  md5: 412844eccbc36c8a493f3846b6b8d736

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - matplotlib
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.sp
    - cmake
    - pkg-config
    - boost 1.62.*

  run:
    - python
    - matplotlib
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.sp
    - boost 1.62.*

test:
  commands:
    - nosetests -sv bob.ip.gabor

  imports:
    - bob
    - bob.ip
    - bob.ip.gabor

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: C++ code and Python bindings for Bob's Gabor wavelet analysis tools

extra:
  recipe-maintainers:
    - 183amir
