travis:
  secure:
    BINSTAR_TOKEN: wDjkAF1243MOZ1FSfeRrrd/NRQaATR5FR3XWJIDNNldUoVeaoL8NMoT/3MIy/mAOBmGp6S90gxrUhsXompnFZUI6MUCmPmLKp273WNrCa6RYYxld6eRYFu08TnEsNH8oRigWp9zlHhIpsjkdauQUSP93wWQnwsG4TS2cPdRqnCkwx04GrhIaH0SK/OmpFLtnAcGe4Qhep0FyT0JSevXGhwDDQ8GO3O494091wwv98U2NAsbbnnqZW8Qho2Cu/01d+AIXOC4o7klKuZNcWraDjbGQNVNwxwudWrOyOwuYW6uJ43YjOIia0ZuYyy3wO2nkXUfH64TMLOhAQ8tLj/mkoJOjCIzekiBSNM0n8fnb8N1DZiFrN7AfVYvwC+6p7DHCISDpvXI+kU58ffZt5xgREd7QFnjuDXVbAHQNMg9FPit3JSdpN9F2jNVb/K3gtQe16ja9zpzBwCUkhQVsJoPOqeMTHp54Tkgpq3xiMfnlFHr5TXHFkhlnyA302aXzYvKdocCCkUPfzZdJbeOxfuQzJeF25U5+Fky5Ns6m6fUur3725cXfRJMd0n5rTIDryHmN5Wv5fObQCVCBPs5h6wMygu2h/kNEPoM9f0uzIakelcouUKaF7b9kBEzTXd00DQUZcQq/kQeAr8G96ThJmtiFrSQYOYLs0kUuwTE1lAn9dcI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
